# Performs test coverage of project's libraries using cargo-tarpaulin and message-generator, then 
# generates results using codecov.io.
# The follow flags are used when executing cargo-tarpaulin:
# -- features: Includes the code with the listed features. The following features result in a
#    tarpaulin error and are NOT included: derive, alloc, arbitrary-derive, attributes, and
#    with_serde
# --lib: Only tests the package's library unit tests. Includes protocols, and utils (without the
#   exclude-files flag, it includes this example because it contains a lib.rs file)
# --exclude-files examples/*: Excludes all projects in examples directory (specifically added to
#   ignore examples that that contain a lib.rs file like interop-cpp)
# --timeout 120: If unresponsive for 120 seconds, action will fail
# --fail-under 40: If code coverage is less than 40%, action will fail
# --out Xml: Required for codecov.io to generate coverage result
# test/message-generator/test/cov/cov_test.json is run for MG coverage of the

name: MG Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codecov_test:
    name: MG Test Coverage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-20.04
        include:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - uses: actions-rs/toolchain@v1

        with:
          toolchain: nightly
          override: true
      - name: Run mg codecov tests
        run: sh ./mg-codecov-tests.sh
